### ISSUE TITLE
update nbvv to use latest w3cv

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nbvv#23]
Already started in #22 but needs to get a version bump and update for any additional changes since this PR was last modified.

**Comment by ShrimpCryptid** [comment]
I think I resolved most of the core issues, though I need to update font use in w3cv. This branch will be broken until the new package is released and the dependencies are rebuilt in `yarn.lock`.

**Comment by ShrimpCryptid** [comment]
Also see https://github.com/allen-cell-animated/website-3d-cell-viewer/pull/234 for a fix to embedded fonts not using Open Sans.
